sudo: required
services:
  - docker

before_install:
  - docker build -t haiderlasani/react -f Dockerfile.dev .
script:
  - docker run haiderlasani/react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-200132636904"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    - "$AWS_SECRET_KEY"