sudo: required
services:
  - docker
language: "node_js"

before_install:
  - docker build -t haiderlasani/react -f Dockerfile.dev .
script:
  - docker run haiderlasani/react npm run test -- --coverage